### ISSUE TITLE
apm being finicky

### ISSUE THREAD

**Issue by nacjm** [zenith391/Fuchas#15]
Apparently apm is being very finicky with allowing packages to install.
 Stardust won't install, and apm errors out when doing apm update with a concatenation error. parse error on install of other packages as well.
Any ideas why that may be?
Running on latest stable version since dev branch won't even install atm

**Comment by zenith391** [comment]
Dev branch has been removed for now (but release branch contains latest features), stardust is installed by default on Fuchas, and can you please show the errors when you do `apm update` ?

**Comment by Tavyza** [comment]
![Screenshot from 2024-09-30 10-15-21](https://github.com/user-attachments/assets/999cb652-b36a-4395-898f-c4adb352bff3)
