### ISSUE TITLE
Install using BASE_DIR fails

### ISSUE THREAD

**Issue by skwerlman** [zenith391/Fuchas#20]
**Describe the bug**
Installs using BASE_DIR are broken

**To Reproduce**
1. Boot from an OpenOS floppy with some unformatted drive attached
2. Set `BASE_DIR` and `CPIO_BASE_DIR` to some location (I used a RAID mounted at `/mnt/de7`)
3. Run the installer
4. Install appears to succeed
5. On reboot, get the following bluescreen:
```
Unrecoverable Error
Fuchas/Kernel/boot.lua:102: attempt to call a nil value (global 'loadfile')
```

**Expected behavior**
Installs with a custom BASE_DIR should work

**Version**
This is occuring with the latest release.cpio

**Platform**
All

**Comment by zenith391** [comment]
Strange, can you send me the content of the file `/mnt/de7/init.lua` ?
(to do that boot with an OpenOS floppy and do `cat /mnt/de7/init.lua` and send me a screenshot of that)

**Comment by skwerlman** [comment]
uploaded the init.lua here: https://gist.github.com/skwerlman/7f9758c9a4a45f1a5e0616a128b2ac73

**Comment by skwerlman** [comment]
reading through it myself, it seems like the `_G.loadfile` bit is missing from the "no OpenOS" shortcut on line 27.
https://gist.github.com/skwerlman/7f9758c9a4a45f1a5e0616a128b2ac73#file-init-lua-L27-L30

After adding it back, the OS boots most of the way, before hanging at `(5/5) Loading 03_os.lua..` until i click on the screen, when it finally drops into a shell

**Comment by zenith391** [comment]
Ok thank you, i'll put the changes on main branch.
