### ISSUE TITLE
desktop doesn't open

### ISSUE THREAD

**Issue by purpelpower** [zenith391/Fuchas#26]
so when im running fuchas it gives me this error = check the photo

![Knipsel](https://user-images.githubusercontent.com/71569824/107153573-8d20fb00-696e-11eb-8892-2232f96cf83c.PNG)

**Comment by zenith391** [comment]
Yea Fushell didn't handled running a directory, however why you tried to run `fuchas` inside of Fuchas ?

**Comment by purpelpower** [comment]
because i wanted the desktop
