### ISSUE TITLE
Installation CPIO fails to download due to invalid signature

### ISSUE THREAD

**Issue by kcinnaJlol** [zenith391/Fuchas#28]
**Describe the bug**
The OpenOS installer fails to download the installation archive because the signature is invalid.

**To Reproduce**
1. Start OpenOS installer
2. Hit enter twice to begin installation

**Expected behavior**
The expected behavior would be to have the installation complete normally.

**Version**
This bug appears to be introduced in commit a2e4f34

**Platform**
Not applicable since the installer for OpenOS is universal across all platforms.

**Comment by zenith391** [comment]
Does it work again now? I tried to fix the website and it works on my side
