### ISSUE TITLE
Fuchas Installer error when fetching files

### ISSUE THREAD

**Issue by MiguelEXE** [zenith391/Fuchas#29]
**Describe the bug**
Fuchas Installer gives the error "byte: string expected, got nil at line 55" when fetching files

**To Reproduce**
1. Launch Fuchas Installer
2. Choose 'Erase "OpenOS"' or 'Keep "OpenOS", go dual-boot'
3. Choose 'Stable release' or 'Dev release (currently paused, don't use that)'

**Expected behavior**
Install a clean version of Fuchas.

![image](https://user-images.githubusercontent.com/52385139/135740554-685c2908-f433-47cd-a251-4ed74f537f22.png)

**Info:**
The computer is running an native Lua bios
Architecture is Lua 5.3
Installer command: "pastebin run EbHYvEE8" (from README.md)

**Comment by DimitarBogdanov** [comment]
I'm having the exact same issue, tried using both release channels, dual boot and erasing (although they claim to do the same thing), no luck :(

**Comment by Lloydplays** [comment]
same

**Comment by AxolotlGuy** [comment]
I know this issue is very old, but i'm having the exact problem. Could you please fix it?

**Comment by Bioscreeper** [comment]
It is still broken, does it work for you, Zenith?

**Comment by Bioscreeper** [comment]
Error: stream:read(1) returns nil, because the new file
cpioBaseDir .. "fuchas.cpio"
is created.

**Comment by MiguelEXE** [comment]
![2023-11-10_20 50 49](https://github.com/zenith391/Fuchas/assets/52385139/dae4e663-fd64-4d19-a7af-79b942f46210)
still giving the error

**Comment by MiguelEXE** [comment]
> ![2023-11-10_20 50 49](https://user-images.githubusercontent.com/52385139/282195097-dae4e663-fd64-4d19-a7af-79b942f46210.png) still giving the error

[Fuchas installer error message](https://pastebin.com/FekePa53)

**Comment by MiguelEXE** [comment]
trying to download the cpio using wget command gives this
![image](https://github.com/zenith391/Fuchas/assets/52385139/fb395d53-caaa-4f4e-b7b5-be90c465779c)

**Comment by MiguelEXE** [comment]
OK, this is a java certificate error and not a installer problem.
If you are having this installer issues try to install the [remote certificate](https://drive.google.com/file/d/183atH_BFbrT5TQ3J2P2eW3GuVvOYD42g/view?usp=sharing)
