### ISSUE TITLE
Install is broken

### ISSUE THREAD

**Issue by Adorable-Catgirl** [zenith391/Fuchas#4]
Installation doesn't download important files (`Fuchas/Libraries/keyboard.lua`) and/or names are broken (`Users/Shared/Libraries/libxml.lua` -> `Users/Shared/Libraries/xml.lua`)

Currently, I'm working on a new installer, and all you have to do is generate a binary CPIO file (say using `find . -depth | grep -v .git | cpio -oHbin > fuchaspkg.cpio`). Will make a PR when it's ready.

**Comment by zenith391** [comment]
I know installation is often broken, and thanks you a lot about that new installation procedure, i would like to know more about it..
